<?php
include("../templates/header.html");
echo"<title>accueil</title></head>";
echo"<body>";
include("../templates/navbar.html");
echo"<h2>Calculer à partir d'un fichier CSV</h2>";
echo"<form method='post'>";
echo"<label for='csvFile'>Importez votre fichier CSV :</label>";
echo"<input type='file' id='csvFile' name='csvFile' accept='.csv''>";
echo"<button type='submit' name='OK' >OK</button>";
echo"<label for='calcul'>Sélectionnez votre calcul</label>";
echo"<select name='calcul' id='calcul'>";
echo"<option value='moyenne'>Moyenne</option>";
echo"<option value='écarttype'>Ecart-type</option>";
echo"<option value='esperance'>Esperance</option>";
echo"<option value='variance'>Variance</option>";
echo"</select>";
echo"<button type='submit' name='Calculer' >Calculer</button>";
echo"</form>";
include("../templates/footer.html");